// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi9dp5E4UF-fF0wqG2jCpbRcH9EZ61lzk',
    appId: '1:360079802418:web:599531e2dd7bac7b8f3c2b',
    messagingSenderId: '360079802418',
    projectId: 'kolos-app-a9421',
    authDomain: 'kolos-app-a9421.firebaseapp.com',
    storageBucket: 'kolos-app-a9421.firebasestorage.app',
    measurementId: 'G-W80GVRNFL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc055pP4bMsUfigzFBLhvXh5851xOBNPQ',
    appId: '1:360079802418:android:f559bf893a9b37258f3c2b',
    messagingSenderId: '360079802418',
    projectId: 'kolos-app-a9421',
    storageBucket: 'kolos-app-a9421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHrPox4VlgTz9q5daHoyxvMe7i7dk3CS8',
    appId: '1:360079802418:ios:3ef86e957bf6a5d08f3c2b',
    messagingSenderId: '360079802418',
    projectId: 'kolos-app-a9421',
    storageBucket: 'kolos-app-a9421.firebasestorage.app',
    iosBundleId: 'com.example.kolosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHrPox4VlgTz9q5daHoyxvMe7i7dk3CS8',
    appId: '1:360079802418:ios:3ef86e957bf6a5d08f3c2b',
    messagingSenderId: '360079802418',
    projectId: 'kolos-app-a9421',
    storageBucket: 'kolos-app-a9421.firebasestorage.app',
    iosBundleId: 'com.example.kolosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi9dp5E4UF-fF0wqG2jCpbRcH9EZ61lzk',
    appId: '1:360079802418:web:c55e089166f411448f3c2b',
    messagingSenderId: '360079802418',
    projectId: 'kolos-app-a9421',
    authDomain: 'kolos-app-a9421.firebaseapp.com',
    storageBucket: 'kolos-app-a9421.firebasestorage.app',
    measurementId: 'G-GN9RLC3V13',
  );
}
